version: '2'
services:
  mongodb:
    image: mongo:8.0.9
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/config:/data/configdb
    env_file:
      - ./mongo/app.env

networks:
  net:
    driver: bridge
